spring.application.name=WebAttack

# Thymeleaf Ã©ÂÂÃ§Â½Â®
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# Ã¦ÂÂ°Ã¦ÂÂ®Ã¥ÂºÂÃ©ÂÂÃ§Â½Â®Ã¯Â¼ÂÃ¨Â¯Â·Ã¦Â Â¹Ã¦ÂÂ®Ã¥Â®ÂÃ©ÂÂÃ¦ÂÂÃ¥ÂÂµÃ¤Â¿Â®Ã¦ÂÂ¹Ã¯Â¼Â
spring.datasource.url=mysql://root:rUWxZTssWOXkXpBBhDZNEYUmRIEjsuGw@crossover.proxy.rlwy.net:44507/railway
spring.datasource.username=root
spring.datasource.password=rUWxZTssWOXkXpBBhDZNEYUmRIEjsuGw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Ã©ÂÂÃ§Â½Â®
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Ã¦ÂÂÃ¤Â»Â¶Ã¤Â¸ÂÃ¤Â¼Â Ã©ÂÂÃ§Â½Â®
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Ã¦ÂÂÃ¥ÂÂ¡Ã¥ÂÂ¨Ã§Â«Â¯Ã¥ÂÂ£
server.port=8080
