spring.application.name=WebAttack

# Thymeleaf ÃÂ©ÃÂÃÂÃÂ§ÃÂ½ÃÂ®
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# ÃÂ¦ÃÂÃÂ°ÃÂ¦ÃÂÃÂ®ÃÂ¥ÃÂºÃÂÃÂ©ÃÂÃÂÃÂ§ÃÂ½ÃÂ®ÃÂ¯ÃÂ¼ÃÂÃÂ¨ÃÂ¯ÃÂ·ÃÂ¦ÃÂ ÃÂ¹ÃÂ¦ÃÂÃÂ®ÃÂ¥ÃÂ®ÃÂÃÂ©ÃÂÃÂÃÂ¦ÃÂÃÂÃÂ¥ÃÂÃÂµÃÂ¤ÃÂ¿ÃÂ®ÃÂ¦ÃÂÃÂ¹ÃÂ¯ÃÂ¼ÃÂ
spring.datasource.url=jdbc:mysql://root:rUWxZTssWOXkXpBBhDZNEYUmRIEjsuGw@crossover.proxy.rlwy.net:44507/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rUWxZTssWOXkXpBBhDZNEYUmRIEjsuGw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ÃÂ©ÃÂÃÂÃÂ§ÃÂ½ÃÂ®
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ÃÂ¦ÃÂÃÂÃÂ¤ÃÂ»ÃÂ¶ÃÂ¤ÃÂ¸ÃÂÃÂ¤ÃÂ¼ÃÂ ÃÂ©ÃÂÃÂÃÂ§ÃÂ½ÃÂ®
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ÃÂ¦ÃÂÃÂÃÂ¥ÃÂÃÂ¡ÃÂ¥ÃÂÃÂ¨ÃÂ§ÃÂ«ÃÂ¯ÃÂ¥ÃÂÃÂ£
server.port=8080
